name: 📚 Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    uses: echecsjs/.github/.github/workflows/docs.yml@main
    secrets: inherit
