name: 🚀 Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: echecsjs/.github/.github/workflows/release.yml@main
    secrets: inherit
