name: Setup

on:
  workflow_call:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 'node'
          registry-url: 'https://registry.npmjs.org'
          scope: '@echecs'
      - name: Install dependencies
        run: pnpm install
